a, b, c = int(input()), int(input()), int(input())
x, y, z = int(input()), int(input()), int(input())
i1 = (a // x) * (b // y) * (c // z)
i2 = (a // x) * (b // z) * (c // y)
i3 = (b // x) * (a // y) * (c // z)
i4 = (b // x) * (a // z) * (c // y)
i5 = (c // x) * (b // y) * (a // z)
i6 = (c // x) * (b // z) * (a // y)
print(max(i1, i2, i3, i4, i5, i6))
